### PR TITLE
Added language as parameter on Purchase (Register.aspx)

### PR DESCRIPTION
**Pull request by csakshaug**
Added language as parameter, so it easier to get correct language when you using agreements (paypal, mobilepay, vipps etc) with netsaxept

### CODE REVIEW

**Comment by csakshaug** [comment]
Can someone take a look at it? @ronnyvv @philsturgeon @alexbilbie @johnkary @bencorlett

**Comment by johnkary** [comment]
Code-wise it looks good to me.

However I am not familiar with how the "language" parameter is used by netaxept. I can't confirm if "language" would be used properly by the API.

**Comment by csakshaug** [comment]
@johnkary https://shop.nets.eu/nb/web/partners/register search after language

I also want to add the missing "Query" feature in a own pull request.

Alle this is important to integrate netaxept to vipps, mobilepay, paypal etc..

If you guys want I can help you with maintaining this driver.

**Comment by delatbabel** [comment]
Further PRs are always welcome of course.

**Pull request merged**
