### PR TITLE
Omnipay v3 compatibility and removed unecessary var_dump in a test.

### PR DESCRIPTION
**Pull request by erikstorli**
Omnipay v3 compatibility according to the upgrade-guide. Had to edit composer.json due to the new 3.0-packages.

### CODE REVIEW

**Comment by erikstorli** [comment]
Only tests failing are pre-php5.6 due to compatibility with Omnipay 3.

**Comment by barryvdh** [comment]
Can you bump the branch alias and remove 5.6 in that case? I believe it should probably work on 5.6 though

**Comment by barryvdh** [comment]
Oh 5.6 minimum is fine, can you update Travis config?

**Comment by erikstorli** [comment]
Is this good?

**Pull request merged**
